import"./assets/styles-NaGSvo1h.js";import{a as A,i as H,d as x}from"./assets/vendor-DOQaTVno.js";const F={page:1,limit:12,skip:0,total:0,totalPages:0};let r={...F};function m({page:t,total:e,reset:o=!1}={}){if(o){r={...F};return}typeof t=="number"&&t>0&&(r.page=t),typeof e=="number"&&e>=0&&(r.total=e,r.totalPages=Math.ceil(r.total/r.limit))}const g=A.create({baseURL:"https://dummyjson.com"}),V=async()=>["all",...(await g.get("/products/category-list")).data];//!======================================================
const R=async(t=1)=>{const e=L({limit:12,currentPage:t});return(await g.get("/products",{params:e})).data},z=async({selectedCategory:t,currentPage:e=1})=>{const o=L({limit:12,currentPage:e});return(await g.get(`/products/category/${t}`,{params:o})).data},J=async t=>(await g.get(`/products/${t}`)).data,K=async({query:t,currentPage:e=1})=>{const o=L({limit:12,currentPage:e,q:t});return(await g.get("/products/search",{params:o})).data};//!======================================================
function L({limit:t,currentPage:e,...o}){const s=(e-1)*t;return{...o,limit:t,skip:s}}const a={categoryListEl:document.querySelector(".js-categories-list"),productsListEl:document.querySelector(".js-products-list"),notFoundEl:document.querySelector(".js-not-found"),loaderEl:document.querySelector(".js-loader"),loadMoreBtnEl:document.querySelector(".js-load-more-btn"),closeModalBtnEl:document.querySelector("[data-modal-close]"),modalEl:document.querySelector("[data-modal]"),modalProductEl:document.querySelector(".js-modal-product"),searchFormEl:document.querySelector(".js-search-form"),searchFormSubmitBtnEl:document.querySelector(".js-search-form__btn-submit"),searchFormClearBtnEl:document.querySelector(".js-search-form__btn-clear")};//! Event Listeners ======================================================
a.closeModalBtnEl.addEventListener("click",b);a.modalEl.addEventListener("click",Q);//! Handlers======================================================
function N(){a.modalEl.classList.add("modal--is-open"),document.addEventListener("keydown",$)}function b(){a.modalEl.classList.remove("modal--is-open"),document.removeEventListener("keydown",$)}function $(t){t.key==="Escape"&&b()}function Q(t){t.target===a.modalEl&&b()}const U=t=>` <li class="categories__item">
             <button class="categories__btn js-categories__btn" type="button">${t}</button>
           </li>
        `,Y=t=>t.map(U).join(`
`),G=t=>{const e=Y(t);a.categoryListEl.innerHTML=e},W=t=>{const{id:e,thumbnail:o,title:s,brand:c="",category:i,price:d}=t;return`<li class="products__item js-products__item" data-id="${e}">
            <img class="products__image" src="${o}" alt="${s}" loading="lazy" />
            <p class="products__title">${s}</p>
            ${c?`<p class="products__brand">
                  <span class="products__brand--bold">Brand: ${c}</span>
              </p>`:""}
            <p class="products__category">Category: ${i}</p>
            <p class="products__price">Price: ${d}$</p>
          </li>
        `},X=t=>t.map(W).join(`
`),Z=t=>{const e=X(t);r.page>1?a.productsListEl.insertAdjacentHTML("beforeend",e):a.productsListEl.innerHTML=e},tt=t=>{const{title:e,tags:o,description:s,shippingInformation:c,returnPolicy:i,price:d,images:h}=t,E=h[0],O=Array.isArray(o)?ot(o):"";return`<img class="modal-product__img" src="${E}" alt="${e}" loading="lazy" />
          <div class="modal-product__content">
            <p class="modal-product__title">${e}</p>
              <ul class="modal-product__tags">
                ${O}   
              </ul>
              <p class="modal-product__description">${s}</p>
              <p class="modal-product__shipping-information">Shipping: ${c}</p>
              <p class="modal-product__return-policy">Return Policy: ${i}</p>
              <p class="modal-product__price">Price: ${d} $</p>
              <button class="modal-product__buy-btn" type="button">Buy</button>
          </div>`};function et(t){return`<li class="modal-product__tag">${t}</li>`}function ot(t){return t.map(et).join(`
`)}async function at(t){try{const e=await J(t),o=tt(e);a.modalProductEl.innerHTML=o}catch(e){console.log(e.message),n({message:e.message,type:"error"})}N()}const S=()=>{a.loaderEl.classList.add("visible")},v=()=>{a.loaderEl.classList.remove("visible")},B=()=>{a.loaderEl.classList.remove("load-more")},st=()=>{a.loadMoreBtnEl.classList.remove("is-hidden")},P=()=>{a.loadMoreBtnEl.classList.add("is-hidden")},rt={searchValue:"",selectedCategory:""},j={formData:{...rt}};function w(t,e){const o=JSON.stringify(e);localStorage.setItem(t,o)}function nt(t,e={}){const o=localStorage.getItem(t);try{return o?JSON.parse(o):e}catch(s){return console.warn("Failed to parse localStorage:",s),n({message:s.message,type:"error"}),e}}function ct(t){localStorage.removeItem(t)}const p=Object.freeze({form:"search-form-state"});function lt(){const t=a.productsListEl;if(!(t!=null&&t.children.length))return;let e=t.children.length-r.limit;e=Math.max(0,e);const o=t.children[e],s=t.children[e+1]||o;if(!o)return;const c=(o==null?void 0:o.offsetHeight)||0,i=(s==null?void 0:s.offsetHeight)||0,d=getComputedStyle(t),h=parseFloat(d.gap)||0,E=c+i+h;window.scrollBy({top:E,behavior:"smooth"})}let{initialFormData:it,formData:M}=j;//! Load functions ======================================================
async function dt(){try{const t=await V();G(t);const e=a.categoryListEl.querySelector(".js-categories__btn"),o=e.textContent==="all";e&&o&&e.classList.add("categories__btn--active")}catch(t){console.log(t.message),n({message:t.message,type:"error"})}}async function f({selectedCategory:t="",currentPage:e=1}){let o;const s=t&&t!=="all";try{s?o=await z({selectedCategory:t,currentPage:e}):o=await R(e),m({total:o.total,page:e}),T(o.products),v()}catch(c){console.log(c.message),n({message:c.message,type:"error"})}}async function C({searchValue:t}){B(),S();try{const e=await K({query:t,currentPage:r.page});m({total:e.total,page:r.page}),pt(r),T(e.products),v()}catch(e){console.log(e.message),n({message:e.message,type:"error"})}}//! Categories and products ======================================================
function ut(t){return(t==null?void 0:t.length)===0}function T(t){if(ut(t)){a.productsListEl.innerHTML="",a.notFoundEl.classList.add("not-found--visible"),P();return}else a.notFoundEl.classList.remove("not-found--visible"),Z(t),r.page>1&&lt(),I()}function k({targetEl:t,reset:e=!1}){const o=document.querySelector(".categories__btn--active");o&&(o.classList.remove("categories__btn--active"),e)||t&&t.classList.add("categories__btn--active")}//! Form helpers ======================================================
function y(t){a.searchFormSubmitBtnEl.disabled=!q(t)}function q(t){return((t==null?void 0:t.searchValue.trim())??"").length>0}function mt(t){return Object.fromEntries(Object.entries(t).map(([e,o])=>[e,o.trim()]))}function D(){a.searchFormEl.reset(),f(),M={...it},M.searchValue="",ct(p.form),y()}function gt(t){try{const e=nt(p.form);e&&typeof e=="object"&&Object.keys(t).forEach(s=>{t[s]=e[s]||""});const o=a.searchFormEl.elements.searchValue;o&&(o.value=t.searchValue,y(t))}catch(e){console.log(e),n({message:e.message,type:"error"})}}function I(){if(r.page>=r.totalPages){P();return}st()}function pt(t){t.page===1&&t.totalPages!==0?n({message:`Total pages: ${t.totalPages}`}):t.totalPages===0?n({message:"Nothing found"}):t.page===t.totalPages&&n({message:"This is the last page"})}function n({message:t,type:e="info"}){H[e]({message:t})}let{formData:l,searchValue:u}=j,{selectedCategory:_}=l;async function ft(){await dt(),await f({currentPage:r.page})}async function yt(t){B(),S(),t.target.classList.contains("js-categories__btn")&&(u="",k({targetEl:t.target}),_=t.target.textContent,await f({selectedCategory:_,currentPage:1}),m({reset:!0}))}function ht(t){const e=t.target.closest(".js-products__item");e&&at(e.dataset.id)}async function Et(){S(),m({page:r.page+1}),a.loadMoreBtnEl.disabled=!0,P();try{u?await C({searchValue:u}):await f({selectedCategory:_,currentPage:r.page})}catch(t){console.log(t.message),n({message:t.message,type:"error"})}finally{I(),a.loadMoreBtnEl.disabled=!1,v()}}function _t(t){const{name:e,value:o}=t.target;e in l&&(l[e]=o,w(p.form,l)),y(l)}function Lt(t){t.preventDefault();const e=mt(l);if(!q(e)){y(e);return}l={...e},w(p.form,l),u=l.searchValue,m({reset:!0}),C({searchValue:u}),k({reset:!0}),D()}gt(j.formData);//!======================================================
document.addEventListener("DOMContentLoaded",ft);a.categoryListEl.addEventListener("click",yt);a.productsListEl.addEventListener("click",ht);a.searchFormEl.addEventListener("input",x(_t,200));a.searchFormEl.addEventListener("submit",Lt);a.searchFormClearBtnEl.addEventListener("click",D);a.loadMoreBtnEl.addEventListener("click",Et);
//# sourceMappingURL=index.js.map
